### ISSUE TITLE
ImportError: No module named 'filexor' after pip install.

### ISSUE THREAD

**Issue by reillysiemens** [PhillipNordwall/FileXor#1]
After attempting to install `FileXor` with `pip` via

``` shell
pip install git+https://github.com/phillipnordwall/FileXor.git@master
```

the following stack trace was generated:

``` python
Traceback (most recent call last):
  File "/home/tucker/.virtualenvs/FileXor/bin/FileXor", line 9, in <module>
    load_entry_point('FileXor==0.2.1a1', 'console_scripts', 'FileXor')()
  File "/home/tucker/.virtualenvs/FileXor/lib/python3.4/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/tucker/.virtualenvs/FileXor/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/tucker/.virtualenvs/FileXor/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/tucker/.virtualenvs/FileXor/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'filexor'
```

This is caused by the fact that the `entry_points` argument in `setup.py` has a console script (`'FileXor=filexor.py:main'`) pointing to a module (`filexor.py`) which does not exist. One way this could be fixed would be to move the `bin/filexor.py` script into the extant `FileXor` module and change the entry point in `setup.py` to use that instead.

**Comment by PhillipNordwall** [comment]
Thank you, your fix has been merged in.
